apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: pingpong
  name: pong
  labels:
    app: pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pong
  template:
    metadata:
      labels:
        app: pong
    spec:
      containers:
      - name: pong
        image: eu.gcr.io/lia2-2023-385111/joakim/pong:v0.0.1
        ports:
        - containerPort: 8080
